python src/dataset/netBrief.py -p "data/epaNet/data-water-epanet/Richmond_skeleton.inp"
python src/dataset/netBrief.py -p "data/epaNet/data-water-epanet/Richmond.inp"
python src/dataset/netBrief.py -p "data/epaNet/data-water-epanet/VanZyl.inp"
python src/dataset/netBrief.py -p "data/epaNet/EPANET/example-networks/Net1.inp"
python src/dataset/netBrief.py -p "data/epaNet/EPANET/example-networks/Net2.inp"
python src/dataset/netBrief.py -p "data/epaNet/EPANET/example-networks/Net3.inp"
python src/dataset/netBrief.py -p "/data/zsc/Pipeline/data/epaNet/Micropolis_TEVA-SPOT_Adjusted_PumpCurve3&4.inp"
python src/dataset/netBrief.py -p "/data/zsc/Pipeline/data/epaNet/Net3_(BWSN-2)_Morph_Error_Free_1s-WQ.inp"
python src/dataset/netBrief.py -p "/data/zsc/Pipeline/data/epaNet/Net3_EPANET-EXAMPLE_No_Demand_Change.inp"
# python src/dataset/netBrief.py -p "/data/zsc/Pipeline/data/epaNet/Net3_EPANET-EXAMPLE.inp"